# vim:fileencoding=utf-8:foldmethod=marker

include Catppuccin-Mocha.conf

# Font
font_size        12.0
font_family      family="Maple Mono NF"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Cursor
cursor_trail 1

# Window
window_margin_width 21.75
background_opacity 0

# Terminal features
copy_on_select yes
strip_trailing_spaces smart

# Keybinds
map ctrl+c copy_or_interrupt
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0 
