# Font
font_family      family="CaskaydiaCove Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0

# Cursor
cursor_shape beam
cursor_trail 1
cursor_trail_color #b4befe

# Padding
window_margin_width 21.75

# Opacity & Blur
background_opacity 0.5
background_blur 1

# Terminal features
copy_on_select yes
strip_trailing_spaces smart

# Key bindings for common actions
map ctrl+c copy_or_interrupt
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# Shell integration
shell fish
shell_integration enabled

# Catppuccin-Mocha
include current-theme.conf
