ELECTRON_OZONE_PLATFORM_HINT=auto
LIBVA_DRIVER_NAME=nvidia
__GLX_VENDOR_LIBRARY_NAME=nvidia
NVD_BACKEND=direct
QT_QPA_PLATFORMTHEME=qt6ct
QT_QPA_PLATFORMTHEME_QT6=qt6ct
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
INPUT_METHOD=fcitx
TERMINAL=kitty
__GL_SHADER_DISK_CACHE_PATH=/home/meow/.cache/nvidia
CUDA_CACHE_PATH=/home/meow/.cache/nvidia
